package amorphia.alloygery.content.material;

import amorphia.alloygery.Alloygery;
import amorphia.alloygery.content.item.ModMiningLevels;
import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import net.minecraft.util.Identifier;

public class AlloygeryMaterials
{
//	public static final DefaultedRegistry<AlloygeryMaterial> ALLOYGERY_MATERIALS = FabricRegistryBuilder
//			.createDefaulted(AlloygeryMaterial.class, Alloygery.identifier("materials"), Alloygery.identifier("materials/unknown"))
//			.attribute(RegistryAttribute.SYNCED)
//			.buildAndRegister();

	public static final BiMap<Identifier, AlloygeryMaterial> ALLOYGERY_MATERIALS = HashBiMap.create();

	public static final AlloygeryMaterial UNKNOWN = registerMaterial("unknown", new AlloygeryMaterial("unknown"));
	public static final AlloygeryMaterial HIDDEN = registerMaterial("hidden", new AlloygeryMaterial("hidden"));

	public static final AlloygeryMaterial TIN;
	public static final AlloygeryMaterial COPPER;
	public static final AlloygeryMaterial BRONZE;
	public static final AlloygeryMaterial IRON;
	public static final AlloygeryMaterial GOLD;
	public static final AlloygeryMaterial EMERALD;
	public static final AlloygeryMaterial ANTANIUM;
	public static final AlloygeryMaterial DIAMOND;
	public static final AlloygeryMaterial STEEL;
	public static final AlloygeryMaterial NETHERITE;
	public static final AlloygeryMaterial NICKEL;
	public static final AlloygeryMaterial INVAR;
	public static final AlloygeryMaterial CONSTANTAN;
	public static final AlloygeryMaterial CUPRONICKEL;
	public static final AlloygeryMaterial TITANIUM;
	public static final AlloygeryMaterial TITANIUM_GOLD;
	public static final AlloygeryMaterial NITINOL;

	public static final AlloygeryMaterial VANILLA_STICK;
	public static final AlloygeryMaterial LEATHER;

	public static void init(){}

	static AlloygeryMaterial registerMaterial(String name, AlloygeryMaterial material)
	{
		return register(Alloygery.identifier("materials/" + name), material);
	}

	public static AlloygeryMaterial register(Identifier identifier, AlloygeryMaterial material)
	{
		ALLOYGERY_MATERIALS.put(identifier, material);
		return material;
	}

	static
	{
		TIN = registerMaterial("tin", new AlloygeryMaterial.AlloygeryMaterialBuilder("tin")
				.category("metal")
				.color(14547455)
				.repair_ingredient_tag("c:tin_ingots")
				.build());

		COPPER = registerMaterial("copper", new AlloygeryMaterial.AlloygeryMaterialBuilder("copper")
				.category("metal")
				.color(15433553)
				.repair_ingredient_tag("c:copper_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.STONE)
						.durability(150)
						.mining_speed(4.0f)
						.attack_damage(1.0f)
						.enchantability(10)
						.luck(3.0f)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-100)
						.mining_speed(-2.0f)
						.attack_damage(-2.0f)
						.luck(1.0f)
						.durability_multiplier(0.7f)
						.mining_speed_multiplier(1.1f)
						.attack_damage_multiplier(0.4f)
						.luck_multiplier(1.5f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-100)
						.attack_speed(-0.1f)
						.attack_damage(-1.0f)
						.luck(1.0f)
						.durability_multiplier(0.7f)
						.mining_speed_multiplier(0.6f)
						.attack_damage_multiplier(0.4f)
						.luck_multiplier(1.2f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(5)
						.helmet(1)
						.chestplate(3)
						.leggings(2)
						.boots(1)
						.enchantability(15)
						.build())
				.build());

		BRONZE = registerMaterial("bronze", new AlloygeryMaterial.AlloygeryMaterialBuilder("bronze")
				.category("metal")
				.color(7556410)
				.repair_ingredient_item("alloygery:bronze_ingot")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.BRONZE)
						.durability(250)
						.mining_speed(5.0f)
						.attack_damage(2.0f)
						.enchantability(15)
						.luck(0.5f)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-50)
						.mining_speed(-1.0f)
						.durability_multiplier(1.1f)
						.mining_speed_multiplier(0.7f)
						.attack_damage_multiplier(0.9f)
						.luck_multiplier(1.2f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-75)
						.attack_speed(-0.1f)
						.luck(0.5f)
						.durability_multiplier(0.8f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(0.8f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(15)
						.helmet(2)
						.chestplate(6)
						.leggings(5)
						.boots(2)
						.enchantability(12)
						.build())
				.build());

		IRON = registerMaterial("iron", new AlloygeryMaterial.AlloygeryMaterialBuilder("iron")
				.category("metal")
				.color(15198183)
				.repair_ingredient_tag("c:iron_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.IRON)
						.durability(700)
						.mining_speed(6.0f)
						.attack_damage(2.0f)
						.enchantability(14)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_speed(-1.0f)
						.mining_speed_multiplier(0.9f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability_multiplier(0.9f)
						.mining_speed_multiplier(0.9f)
						.attack_damage_multiplier(0.9f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(15)
						.helmet(2)
						.chestplate(6)
						.leggings(5)
						.boots(2)
						.enchantability(9)
						.build())
				.build());

		//vanilla stats
		GOLD = registerMaterial("gold", new AlloygeryMaterial.AlloygeryMaterialBuilder("gold")
				.category("metal")
				.color(16573743)
				.repair_ingredient_tag("c:gold_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.WOOD)
						.durability(32)
						.mining_speed(12.0f)
						.attack_damage(0.0f)
						.enchantability(22)
						.piglin_loved(true)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-200)
						.mining_speed(3.0f)
						.attack_damage(-3.0f)
						.durability_multiplier(0.6f)
						.mining_speed_multiplier(1.5f)
						.attack_damage_multiplier(0.3f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-300)
						.attack_speed(-0.5f)
						.attack_damage(-2.0f)
						.durability_multiplier(0.5f)
						.mining_speed_multiplier(0.6f)
						.attack_speed_multiplier(1.2f)
						.attack_damage_multiplier(0.3f)
						.build())
				.tool_upgrade(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(-1)
						.durability_multiplier(0.7f)
						.enchantability_multiplier(1.8f)
						.attack_damage_multiplier(0.5f)
						.attack_speed_multiplier(1.2f)
						.mining_speed_multiplier(1.5f)
						.enchantability_multiplier(1.8f)
						.piglin_loved(true)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(7)
						.helmet(2)
						.chestplate(5)
						.leggings(3)
						.boots(1)
						.enchantability(25)
						.piglin_loved(true)
						.build())
				.build());

		EMERALD = registerMaterial("emerald", new AlloygeryMaterial.AlloygeryMaterialBuilder("emerald")
				.category("gem")
				.color(1564002)
				.repair_ingredient_tag("c:emeralds")
				.tool_upgrade(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability_multiplier(1.5f)
						.enchantability(5)
						.luck(5.0f)
						.build())
				.build());

		ANTANIUM = registerMaterial("antanium", new AlloygeryMaterial.AlloygeryMaterialBuilder("antanium")
				.category("metal")
				.color(14329677)
				.repair_ingredient_tag("c:antanium_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.STONE)
						.durability(1000)
						.mining_speed(10.0f)
						.attack_damage(1.0f)
						.enchantability(20)
						.piglin_loved(true)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(-75)
						.attack_damage(-1.0f)
						.durability_multiplier(1.2f)
						.mining_speed_multiplier(1.2f)
						.attack_damage_multiplier(0.6f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.attack_damage_multiplier(0.9f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(20)
						.helmet(2)
						.chestplate(5)
						.leggings(4)
						.boots(2)
						.enchantability(20)
						.piglin_loved(true)
						.build())
				.build());

		DIAMOND = registerMaterial("diamond", new AlloygeryMaterial.AlloygeryMaterialBuilder("diamond")
				.category("gem")
				.color(3402699)
				.repair_ingredient_tag("c:diamonds")
				.make_tool_heads(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.DIAMOND)
						.durability(1561)
						.mining_speed(8.0f)
						.attack_damage(3.0f)
						.enchantability(10)
						.build())
				.tool_upgrade(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(1)
						.durability(500)
						.enchantability(-5)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(33)
						.helmet(3)
						.chestplate(8)
						.leggings(6)
						.boots(3)
						.enchantability(10)
						.toughness(2.0f)
						.build())
				.build());

		STEEL = registerMaterial("steel", new AlloygeryMaterial.AlloygeryMaterialBuilder("steel")
				.category("metal")
				.color(4408907)
				.repair_ingredient_tag("c:steel_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.STEEL)
						.durability(2892)
						.mining_speed(8.0f)
						.attack_damage(6.0f)
						.attack_speed(-0.5f)
						.enchantability(15)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(300)
						.mining_speed(-1.0f)
						.attack_speed(-0.1f)
						.durability_multiplier(1.25f)
						.attack_damage_multiplier(1.2f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(111)
						.attack_speed(0.1f)
						.enchantability_multiplier(0.5f)
						.attack_speed_multiplier(1.2f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(35)
						.helmet(3)
						.chestplate(8)
						.leggings(6)
						.boots(3)
						.enchantability(11)
						.toughness(2.0f)
						.build())
				.build());

		NETHERITE = registerMaterial("netherite", new AlloygeryMaterial.AlloygeryMaterialBuilder("netherite")
				.category("metal")
				.color(5192766)
				.repair_ingredient_tag("c:netherite_ingots")
				.make_tool_heads(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.NETHERITE)
						.durability(2031)
						.mining_speed(9.0f)
						.attack_damage(4.0f)
						.enchantability(15)
						.fireproof(true)
						.build())
				.tool_upgrade(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability_multiplier(1.2f)
						.mining_speed_multiplier(1.1f)
						.attack_damage_multiplier(1.1f)
						.fireproof(true)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(37)
						.helmet(3)
						.chestplate(8)
						.leggings(6)
						.boots(3)
						.enchantability(15)
						.toughness(3.0f)
						.knockback_resistance(0.1f)
						.fireproof(true)
						.build())
				.build());

		NICKEL = registerMaterial("nickel", new AlloygeryMaterial.AlloygeryMaterialBuilder("nickel")
				.category("metal")
				.color(6314062)
				.repair_ingredient_tag("c:nickel_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.NICKEL)
						.durability(1784)
						.mining_speed(8.0f)
						.attack_damage(4.0f)
						.enchantability(15)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(50)
						.mining_speed(-1.0f)
						.durability_multiplier(0.6f)
						.mining_speed_multiplier(0.9f)
						.attack_damage_multiplier(1.1f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability_multiplier(0.9f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(0.7f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(37)
						.helmet(3)
						.chestplate(8)
						.leggings(6)
						.boots(3)
						.enchantability(12)
						.toughness(3.0f)
						.build())
				.build());

		INVAR = registerMaterial("invar", new AlloygeryMaterial.AlloygeryMaterialBuilder("invar")
				.category("metal")
				.color(10789019)
				.repair_ingredient_tag("c:invar_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.NICKEL)
						.durability(3127)
						.mining_speed(7.0f)
						.attack_damage(7.0f)
						.attack_speed(-1.0f)
						.enchantability(2)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(500)
						.mining_speed(-3.0f)
						.attack_speed(-0.5f)
						.attack_damage(2.0f)
						.durability_multiplier(0.5f)
						.enchantability_multiplier(0.1f)
						.mining_speed_multiplier(0.6f)
						.attack_speed_multiplier(0.5f)
						.attack_damage_multiplier(1.3f)
						.luck_multiplier(0.1f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(200)
						.attack_damage(1.0f)
						.enchantability_multiplier(0.2f)
						.mining_speed_multiplier(1.2f)
						.attack_speed_multiplier(0.5f)
						.attack_damage_multiplier(1.3f)
						.luck_multiplier(0.1f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(45)
						.helmet(3)
						.chestplate(9)
						.leggings(7)
						.boots(3)
						.enchantability(10)
						.toughness(3.0f)
						.knockback_resistance(0.1f)
						.build())
				.build());

		CONSTANTAN = registerMaterial("constantan", new AlloygeryMaterial.AlloygeryMaterialBuilder("constantan")
				.category("metal")
				.color(11558984)
				.repair_ingredient_tag("c:constantan_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.NICKEL)
						.durability(2031)
						.mining_speed(5.0f)
						.attack_damage(2.0f)
						.attack_speed(-0.2f)
						.enchantability(15)
						.luck(0.8f)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(55)
						.mining_speed(-2.0f)
						.attack_damage(-1.0f)
						.durability_multiplier(1.025f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(1.1f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.attack_speed(-0.1f)
						.durability_multiplier(0.9f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(0.7f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(40)
						.helmet(3)
						.chestplate(8)
						.leggings(6)
						.boots(3)
						.enchantability(15)
						.toughness(3.0f)
						.build())
				.build());

		CUPRONICKEL = registerMaterial("cupronickel", new AlloygeryMaterial.AlloygeryMaterialBuilder("cupronickel")
				.category("metal")
				.color(5257772)
				.repair_ingredient_tag("c:cupronickel_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.NICKEL)
						.durability(2121)
						.mining_speed(6.0f)
						.attack_damage(5.0f)
						.attack_speed(-0.2f)
						.enchantability(15)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(75)
						.mining_speed(-2.0f)
						.luck(0.5f)
						.durability_multiplier(0.9f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(1.1f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.attack_speed(-0.1f)
						.luck(0.1f)
						.durability_multiplier(0.9f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(0.7f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(40)
						.helmet(3)
						.chestplate(9)
						.leggings(6)
						.boots(3)
						.enchantability(15)
						.toughness(3.0f)
						.build())
				.build());

		TITANIUM = registerMaterial("titanium", new AlloygeryMaterial.AlloygeryMaterialBuilder("titanium")
				.category("metal")
				.color(5990506)
				.repair_ingredient_tag("c:titanium_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.TITANIUM)
						.durability(2221)
						.mining_speed(9.0f)
						.attack_speed(2.0f)
						.attack_damage(4.0f)
						.enchantability(18)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(125)
						.attack_speed(0.5f)
						.durability_multiplier(0.8f)
						.mining_speed_multiplier(0.8f)
						.attack_damage_multiplier(0.7f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(50)
						.mining_speed(0.5f)
						.durability_multiplier(0.9f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(45)
						.helmet(4)
						.chestplate(9)
						.leggings(7)
						.boots(4)
						.enchantability(18)
						.toughness(2.0f)
						.build())
				.build());

		TITANIUM_GOLD = registerMaterial("titanium_gold", new AlloygeryMaterial.AlloygeryMaterialBuilder("titanium_gold")
				.category("metal")
				.color(13086590)
				.repair_ingredient_tag("c:titanium_gold_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.TITANIUM)
						.durability(1600)
						.mining_speed(14.0f)
						.attack_speed(1.5f)
						.attack_damage(3.0f)
						.enchantability(25)
						.piglin_loved(true)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_speed(1.0f)
						.attack_speed(0.2f)
						.durability_multiplier(1.1f)
						.mining_speed_multiplier(1.1f)
						.attack_damage_multiplier(0.8f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_speed(0.5f)
						.attack_damage(1.0f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(47)
						.helmet(4)
						.chestplate(9)
						.leggings(7)
						.boots(4)
						.enchantability(25)
						.toughness(3.0f)
						.piglin_loved(true)
						.build())
				.build());

		NITINOL = registerMaterial("nitinol", new AlloygeryMaterial.AlloygeryMaterialBuilder("nitinol")
				.category("metal")
				.color(6185051)
				.repair_ingredient_tag("c:nitinol_ingots")
				.make_tool_heads(true)
				.make_tool_bindings(true)
				.make_sword_guards(true)
				.make_tool_handles(true)
				.tool_base(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.mining_level(ModMiningLevels.TITANIUM)
						.durability(2471)
						.mining_speed(9.0f)
						.attack_speed(1.0f)
						.attack_damage(5.0f)
						.enchantability(18)
						.build())
				.tool_binding(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(200)
						.attack_damage(1.0f)
						.mining_speed_multiplier(0.7f)
						.attack_damage_multiplier(1.1f)
						.build())
				.tool_handle(new AlloygeryMaterial.ToolPartSettings.ToolPartSettingsBuilder()
						.durability(70)
						.mining_speed(2.0f)
						.build())
				.armor(new AlloygeryMaterial.ArmorPartSettings.ArmorPartSettingsBuilder()
						.durability(50)
						.helmet(4)
						.chestplate(9)
						.leggings(7)
						.boots(4)
						.enchantability(18)
						.toughness(3.0f)
						.knockback_resistance(0.1f)
						.build())
				.build());

		VANILLA_STICK = registerMaterial("wooden", new AlloygeryMaterial.AlloygeryMaterialBuilder("wooden")
				.category("wood")
				.color(6835742)
				.make_tool_handles(true)
				.build());

		LEATHER = registerMaterial("leather", new AlloygeryMaterial.AlloygeryMaterialBuilder("leather")
				.category("hide")
				.color(14117699)
				.make_tool_bindings(true)
				.build());
	}
}
